version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "python-sam-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cimye9j8plsc"
s3_prefix = "python-sam-hello-world"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
